root_config_folder: "configs/depth_estimation"  # This is where all your individual config files are stored

override_present: False

calibration:
  overrides: 
    - "mask_generation.lightweight_segmenter=false"

estimation:
  overrides:
    - "general.min_depth=1"

hydra:
  run:
    dir: .   # This keeps the working directory unchanged (i.e., no new output folder will be created)
  output_subdir: null  # This disables creating the "outputs" directory

